
# Arguements
#  1. uforwarder: fwd-server ['host:port', 'host:port' ]
#  2. hwforwarder: fwd-server, listen [ 'tcp:9997', 'udp:9998', 'splunk_tcp:9999']
#  3. indexer: listen [ 'tcp:9997', 'udp:9998', 'splunk_tcp:9999']
#  4. searchhead: sch-server ['host:port', 'host:port:user:pass']
#  5. cluster_master:
#  6. cluster_searchhead:
#  7. cluster_slave

# basic idea:
# 1. each thread will carry one host and its arguements, so host_parser is to get the values dict for the host.
# 2. hosts values precedences: specific list (so the host list will get its corresponding positions) > value for a role (multiple host with only one value-string) > default value-string

run_roles: ['cluster_master', 'cluster_slave']
host_arguments: ['host', 'platform', 'deploy_dir', 'splunkd_port', 'splunkweb_port', 'pkg', 'replication_factor', 'replication_port', 'search_factor', 'is_upgrade', 'is_backup', 'forward_server', 'listen_type_port', 'search_server', 'is_with_data', 'data_file']


nodes: 
    - role: cluster_master
      host: 'root@qasus-CentOS-5'
      platform: 'Linux'
      deploy_dir: '/home/cchung'
      splunkd_port: '8089'
      splunkweb_port: '8000'
      pkg: 'splunk-5.0.2-155424-SunOS-x86_64.tar.msi'

    - role: cluster_searchhead
      host: ['eserv@sfeserv44', 'eserv@sfeserv45']
      platform: ''
      deploy_dir: ['/home/eserv/', '/home/cchung']
      splunkd_port: '8089'
      splunkweb_port: '8000'
      pkg:

    - role: cluster_slave
      host: ['root@qasus-CentOS-4', 'Administrator@10.160.44.57', 'Administrator@10.160.44.63']
      platform: ['Linux', 'windows', 'windows']
      deploy_dir: ['/home/cchung', '/home/cchung', '/home/cchung']
      pkg: ['splunk-5.0.2-155424-Linux-x86_64.tgz', 'splunk-5.0.3-157096-x64-release.zip', 'splunk-5.0.3-157096-x64-release.zip']


default_auth: 'admin:changeme'
default_deploy_dir: '/home/eserv/'
default_platform: 'Linux' # Linux, Solaris, or Windows
default_splunkd_port: '8089'
default_splunkweb_port: '8000'
default_pkg: 'splunk-5.0.2-155424-SunOS-x86_64.tar.Z'
default_replication_factor: 1 # for cluster_master
default_search_factor: 1 # for cluster_master
default_replication_port: 8889 # for cluster_slave
default_is_upgrade: False # upgrade: stop splunk, dont perform backup (disable boot-start?), install pkg
default_is_backup: False # backup existing splunk instance at deploy_dir
default_forward_server: '' # for fwd
default_listen_type_port: 'tcp:9997'
default_search_server: ''
default_is_with_data: False # send data_file to splunk? (copy data_file to spool)
default_data_file: 'sample_1m.tgz'

