
# Special paramaters used for each role:
#  1. forwarder: fwd-server, listen_type_port, is_with_data, data_file
#  2. indexer: listen_type_port, is_with_data, data_file
#  3. searchhead: search_server (in 'host:port' or 'host:port:user:pass' forms)
#  4. cluster_master: replication_factor, search_factor
#  5. cluster_searchhead: master_uri
#  6. cluster_slave: master_uri, replication_port, listen_type_port, is_with_data, data_file

# For deploying standalone splunk instances, you can use any role name you like, and run 
# "fab deploy_splunk -R $role_name_you_like"

# basic idea:
# 1. each thread will carry one host and its arguements, so host_parser is to get the values dict for the host.
# 2. hosts values precedences: specific list (so the host list will get its corresponding positions) > value for a role (multiple host with only one value-string) > default value-string

host_params: ['role', 'host', 'platform', 'deploy_dir', 'pkg', 'is_send_pkg', 'auth', 'splunkd_port', 'splunkweb_port', 'is_upgrade', 'is_backup', 'replication_factor', 'replication_port', 'search_factor', 'master_uri', 'forward_server', 'listen_type_port', 'search_server', 'is_with_data', 'data_file']

nodes: 
    - role: cluster_master
      host: root@qasus-CentOS-1

    - role: cluster_searchhead
      host: root@qasus-CentOS-2
      master_uri: qasus-CentOS-1:38189

    - role: cluster_slave
      host: ['root@qasus-CentOS-3', 'root@qasus-CentOS-4', 'root@qasus-Centos-5']
      master_uri: qasus-CentOS-1:38189

    - role: forwarder
      host: localhost

# There is no default_host or default_role! Ther are required to execute this fab!
## for all nodes
default_platform: Linux # Linux, Solaris, or Windows
default_deploy_dir: /home/cchung/fab
default_pkg: /home/cchung/splunk/splunk_pkg/splunk-5.0.3-161767-Linux-x86_64.tgz
default_is_send_pkg: True
default_auth: admin:changeme
default_splunkd_port: 38189
default_splunkweb_port: 38100
default_is_backup: False # backup existing splunk instance at deploy_dir, up to 5
default_is_upgrade: False # upgrade: stop splunk, install pkg

## clustering
default_replication_factor: 3            # for cluster_master
default_search_factor: 2                 # for cluster_master
default_master_uri: qasus-CentOS-1:38189 # for cluster_searchhead and slave
default_replication_port: 38888          # for cluster_slave

## fwd
default_forwarder_num: 10 # Not implemented yet.
default_forward_server: ['qasus-centos-1:39996'] # for fwd

## idx or slave
default_listen_type_port: ['tcp:9997', 'udp:9998', 'splunktcp:9996'] #need to be a list now.

## fwd, idx, or slave
default_is_with_data: True # copy data_file to deploy_dir and monitor it
default_data_file: 'data/sample_1m.tgz'

# sh, cluster_sh
default_search_server: ['qasus-centos-3:38189:admin:changeme', 'qasus-centos-4:38189']
