
default_deploy_dir: ''
default_pkg: './splunk-4.3.5-152772-SunOS-x86_64.tar.Z'

hosts: 
    - type: master
      host: ['eserv@sfeserv43']
      platform: 
      deploy_dir: '/export/home/eserv/cchung'
      port: '8089'
      web_port: '8000'
      pkg: 

    - type: searchhead
      host: ['eserv@sfeserv44', 'eserv@sfeserv45']
      platform: ''
      deploy_dir: ['/home/eserv/', '/home/cchung']
      port: '8089'
      web_port: '8000'
      pkg:

    - type: slave
      host: ['eserv@sfeserv46', 'eserv@sfeserv47']
      platform: 
      deploy_dir: ['/home/eserv/']
      port: '8089'
      web_port: '8000'
      pkg: 
