
# Arguements
#  1. uforwarder: fwd-server ['host:port', 'host:port' ]
#  2. hwforwarder: fwd-server, listen [ 'tcp:9997', 'udp:9998', 'splunk_tcp:9999']
#  3. indexer: listen [ 'tcp:9997', 'udp:9998', 'splunk_tcp:9999']
#  4. searchhead: sch-server ['host:port', 'host:port:user:pass']
#  5. cluster_master:
#  6. cluster_searchhead:
#  7. cluster_slave

# basic idea:
# 1. each thread will carry one host and its arguements, so host_parser is to get the values dict for the host.
# 2. hosts values precedences: specific list (so the host list will get its corresponding positions) > value for a role (multiple host with only one value-string) > default value-string

run_roles: ['cluster_master', 'cluster_searchhead', 'cluster_slave']
host_params: ['role', 'host', 'platform', 'deploy_dir', 'pkg', 'is_send_pkg', 'auth', 'splunkd_port', 'splunkweb_port', 'is_upgrade', 'is_backup', 'replication_factor', 'replication_port', 'search_factor', 'master_uri', 'forward_server', 'listen_type_port', 'search_server', 'is_with_data', 'data_file']

# Parameters used for each role:
## cluster_master: replication_factor, search_factor
## cluster_searchhead: master_uri
## cluster_slave: master_uri, replication_port
## searchhead: search-server
## indexer: 
## uforwarder: forward-server
## forwarder: forward-server

nodes: 
    - role: cluster_master
      host: root@qasus-CentOS-1

    - role: cluster_searchhead
      host: root@qasus-CentOS-2
      master_uri: qasus-CentOS-1:38189

    - role: cluster_slave
      host: ['root@qasus-CentOS-3', 'root@qasus-CentOS-4', 'root@qasus-Centos-5']
      master_uri: qasus-CentOS-1:38189

# There is no default_host or default_role! Ther are needed to execute fab!
default_platform: Linux # Linux, Solaris, or Windows
default_deploy_dir: /home/cchung/fab
#default_pkg: /home/cchung/splunk/splunk_pkg/splunk-5.0.1-143156-Linux-x86_64.tgz  
default_pkg: /home/cchung/splunk/splunk_pkg/splunk-5.0.3-161767-Linux-x86_64.tgz
#default_pkg: /home/cchung/splunk/splunk_pkg/splunk-5.0.2.4-156374-Linux-x86_64.tgz
default_is_send_pkg: True
default_auth: admin:changeme
default_splunkd_port: 38189
default_splunkweb_port: 38100
default_is_backup: False # backup existing splunk instance at deploy_dir, up to 5
default_is_upgrade: True # upgrade: stop splunk, install pkg

## Clustering
default_master_uri: 
default_replication_factor: 3 # for cluster_master
default_search_factor: 2 # for cluster_master
default_replication_port: 38888 # for cluster_slave

## Forwarder
default_forwarder_num: 10 
default_forward_server: '' # for fwd

## Indexer
default_listen_type_port: 'tcp:9997'
default_is_with_data: False # send data_file to splunk? (copy data_file to spool)
default_data_file: 'data/sample_1m.tgz'

# Search head
default_search_server: ''
